### ISSUE TITLE
binary BERT protocol support

### ISSUE THREAD

**Issue by henry-hz** [bwegh/erwa#12]
Hi, let me suggest to implement the native binary support, so Erlang will shine and be able to receive many thousands of connections without the hard job of dealing with message conversion for every message. http://bert-rpc.org/

**Comment by bwegh** [comment]
Thanks for the suggestion, 
Which connection are you thinking of? 
Websocket we could just introduce another kind of encoding like wamp-bert. 
Over TCP we should talk to Travendo so a bit gets reserved inside the TCP-Handshake for the protocol.

Anyway it looks very good and I am going to implement it.

Would you mind telling me what you are using it for, I am very interested in the use cases of Erwa.

**Comment by bwegh** [comment]
It is not offically in the spec, yet you can enable it by setting the application env 'erlbin_number' for the raw transport.
For an example see test/roundtrip_SUITE.erl (init_per_suite/1 and pubsub_tcp/1).
