### ISSUE TITLE
Are wamp.session.on_leave metaevents supported?

### ISSUE THREAD

**Issue by wcreek** [bwegh/erwa#17]
While subscribing to wamp.session.on_join and wamp.session.on_leave metaevents I do receive wamp.session.on_join events upon opening a session with awre:connect(Con, Realm)  but I'm not getting any wamp.session.on_leave events upon closing the session with awre:stop_client(Con)

**Comment by bwegh** [comment]
They should be ... I will look into it.
Thanks for reporting

**Comment by wcreek** [comment]
Could the reason be that erwa_session:close_session is not getting invoked?
