### ISSUE TITLE
Question about nessesity sessions registration.

### ISSUE THREAD

**Issue by comtihon** [bwegh/erwa#19]
Good time of the day.
As far as I understand - when new client connects (wamp hello message) - session is registered in `erwa_sessions`, where session data is inserted in ets and calling process is put under monitoring.
My question is - do we really need monitor there?
I think, that when we will have a lot of incoming sessions - registration on single gen_server will be an bottle neck.
If monitor is only need for cleaning session's data from ets - may be it will be better to make ets public with concurrency rw and made cleanup in session's process terminate? 
I can implement it and I think we can get rid of `erwa_sessions` separate process this way.

**Comment by comtihon** [comment]
I found out, that same is with `erwa_routing:connect`, `get_broker`, `get_dialer`. All threads from handlers deal with one gen_server, while processing `hello`.  
I will make concurrent branch and try to refactor this.

**Comment by comtihon** [comment]
less_common_threads branch both in erwa and awre

**Comment by bwegh** [comment]
I guess the best might be just using mnesia.

**Comment by bwegh** [comment]
changed from gen_server to a mnesia table.
