### ISSUE TITLE
Erwa crash when MNESIA schema has been created

### ISSUE THREAD

**Issue by ethrbh** [bwegh/erwa#20]
hello Bas,

Sorry for this ticket, but I think I found an error in erwa. Shortly the problem occurs if MNESIA schema is created and than erwa app is going to start. I try describe how I mean and what I did. So I made a test application, where erwa is a dependency. 

Here are the steps what test app is doing:
1. Start test app what checks a dummy folder in its database dir, and if that is not there, the test app will stop MNESIA and will configure the schema, ect, and halt Erlang VM at the end. 
2. Start test app. It check the dummy folder what is there, and will does nothing.
    I do halt the Erlang VM manually.
3. The 3rd time when test app is started, the dummy folder is there, but erwa crashes when its start up. The crash occurred when erwa creates erwa_pub_rec RAM copy table.

I think erwa should checks table before create is, and contine its flow without creating table if that is exists already.

Please find the test app here: https://github.com/ethrbh/erwa_test

Of course, let me know if I did something wrong, or try use erwa in a wrong way.

The version of erwa I use is this:
    commit 4104b5bf871adee669d838633cb458a421e4cdab
    Author: Bas Wegh <BasWegh@gmx.de>
    Date:   Sun Aug 23 19:58:42 2015 +0200

        Use one table per realm in broker

And please find the console printout about my test:
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erwa_test(master)> _rel/erwa_test_release/bin/erwa_test_release console
	Exec: /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/erts-6.4/bin/erlexec -boot /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/releases/1/erwa_test_release -boot_var ERTS_LIB_DIR /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/erts-6.4/../lib -env ERL_LIBS /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/releases/1/lib -config /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/releases/1/sys.config -args_file /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/releases/1/vm.args -- console
	Root: /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release
	/mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release
	heart_beat_kill_pid = 27771
	Erlang/OTP 17 [erts-6.4] [source] [smp:2:2] [async-threads:10] [kernel-poll:false]

	=INFO REPORT==== 26-Aug-2015::14:15:41 ===
	Stop MNESIA

	=INFO REPORT==== 26-Aug-2015::14:15:41 ===
		application: mnesia
		exited: stopped
		type: permanent

	=INFO REPORT==== 26-Aug-2015::14:15:41 ===
	Create MNESIA schema

	=INFO REPORT==== 26-Aug-2015::14:15:41 ===
	Re-start MNESIA
	heart: Wed Aug 26 14:15:41 2015: Erlang has closed.
	heart: Wed Aug 26 14:15:41 2015: Would reboot. Terminating.
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erwa_test(master)> ls _rel/erwa_test_release/dbase/
	Mnesia
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erwa_test(master)> ls _rel/erwa_test_release/dbase/Mnesia/
	dummy  LATEST.LOG  schema.DAT
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erwa_test(master)> ls _rel/erwa_test_release/dbase/Mnesia/dummy/
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erwa_test(master)> _rel/erwa_test_release/bin/erwa_test_release console
	Exec: /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/erts-6.4/bin/erlexec -boot /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/releases/1/erwa_test_release -boot_var ERTS_LIB_DIR /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/erts-6.4/../lib -env ERL_LIBS /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/releases/1/lib -config /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/releases/1/sys.config -args_file /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/releases/1/vm.args -- console
	Root: /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release
	/mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release
	heart_beat_kill_pid = 27871
	Erlang/OTP 17 [erts-6.4] [source] [smp:2:2] [async-threads:10] [kernel-poll:false]

	===> System info in version "4.12.5", debug level = none <===
	opt_disc. Directory "/mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/dbase/Mnesia" is used.
	use fallback at restart = false
	running db nodes   = ['erwa_test@127.0.0.1']
	stopped db nodes   = [] 
	master node tables = []
	remote             = []
	ram_copies         = [erwa_pub_rec,erwa_session_record]
	disc_copies        = [schema]
	disc_only_copies   = []
	[{'erwa_test@127.0.0.1',disc_copies}] = [schema]
	[{'erwa_test@127.0.0.1',ram_copies}] = [erwa_session_record,erwa_pub_rec]
	4 transactions committed, 0 aborted, 0 restarted, 4 logged to disc
	0 held locks, 0 in queue; 0 local transactions, 0 remote
	0 transactions waits for other nodes: []

	=INFO REPORT==== 26-Aug-2015::14:16:05 ===
		"MNESIA system info"
		tables: yes
	Eshell V6.4  (abort with ^G)
	(erwa_test@127.0.0.1)1> erlang:halt().
	heart: Wed Aug 26 14:16:19 2015: Erlang has closed.
	heart: Wed Aug 26 14:16:19 2015: Would reboot. Terminating.
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erwa_test(master)> _rel/erwa_test_release/bin/erwa_test_release console
	Exec: /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/erts-6.4/bin/erlexec -boot /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/releases/1/erwa_test_release -boot_var ERTS_LIB_DIR /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/erts-6.4/../lib -env ERL_LIBS /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/releases/1/lib -config /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/releases/1/sys.config -args_file /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release/releases/1/vm.args -- console
	Root: /mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release
	/mnt/ethrbh/private/projects/github/erwa_test/_rel/erwa_test_release
	heart_beat_kill_pid = 27918
	Erlang/OTP 17 [erts-6.4] [source] [smp:2:2] [async-threads:10] [kernel-poll:false]

	=INFO REPORT==== 26-Aug-2015::14:16:23 ===
		application: erwa
		exited: {bad_return,
					{{erwa_app,start,[normal,[]]},
					 {'EXIT',
						 {{badmatch,{aborted,{already_exists,erwa_pub_rec}}},
						  [{erwa_publications,create_table,0,
							   [{file,"src/erwa_publications.erl"},{line,38}]},
						   {erwa_app,start,2,
							   [{file,"src/erwa_app.erl"},{line,40}]},
						   {application_master,start_it_old,4,
							   [{file,"application_master.erl"},{line,272}]}]}}}}
		type: permanent
	{"Kernel pid terminated",application_controller,"{application_start_failure,erwa,{bad_return,{{erwa_app,start,[normal,[]]},{'EXIT',{{badmatch,{aborted,{already_exists,erwa_pub_rec}}},[{erwa_publications,create_table,0,[{file,\"src/erwa_publications.erl\"},{line,38}]},{erwa_app,start,2,[{file,\"src/erwa_app.erl\"},{line,40}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,272}]}]}}}}}"}
	Kernel pid terminated (application_controller) ({application_start_failure,erwa,{bad_return,{{erwa_app,start,[normal,[]]},{'EXIT',{{badmatch,{aborted,{already_exists,erwa_pub_rec}}},[{erwa_publicaheart: Wed Aug 26 14:16:25 2015: tiErlang is crashing .. (waiting for crash dump file)

	heart: Wed Aug 26 14:16:25 2015: Would reboot. Terminating.
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erwa_test(master)>  

thanks for your help,
/Robi

**Comment by ethrbh** [comment]
hello,
I have forked your project, and made a fix for the issue, described above. I did not issued a pull request, but I would like to inform you about it. If you have time please take a look at my fix. If you feel this is good enough for you too, maybe you can apply into your master repo.

My forked project can be found: https://github.com/ethrbh/erwa
Take a look at the erwa_publications.erl, erwa_sessions.erl and erwa_broker.erl modules.I added few lines to check MNESIA table and delete that if that exists, before calling "mnesia:create_table" function.

thanks,
/Robi

**Comment by bwegh** [comment]
thank you very much for the effort you put into this, Robi.

I will have a look within the next two days, had a lot of other stuff on my plate.

Cheers,
Bas

**Comment by ethrbh** [comment]
hello,

You are welcome.

br,
/Robi

**Comment by bwegh** [comment]
Thank you for your testing and feedback,
could you please make it a pull request, so I can just use your code.

**Comment by ethrbh** [comment]
hello Bas,

Please find the pull req. here
    https://github.com/bwegh/erwa/pull/21

br,
/Robi
