### ISSUE TITLE
Crash when calling erwa_dealer:get_registration/2 function

### ISSUE THREAD

**Issue by ethrbh** [bwegh/erwa#34]
hello,

I think I have found a bug in ERWA. I have one registered procedure (realm == <<"igs_realm">>, uri == <<"ws.wamp.igs.rpc">>), and erwa crashes when I would read the registered procedure with erwa_dealer:get_registration/2 function. Please see the logs below. Please also let me know if this is not a fault, but I did something wrong.

	(igs@raspberrypi)1> ets:tab2list(erwa_proc_igs_realm).
	[{erwa_procedure,2564013928344347,
					 <<"wamp.subscription.list">>,
					 {{2016,5,26},{8,43,3}},
					 exact,random,[],
					 [2004237930060555],
					 0},
	 {erwa_procedure,4836601136068951,
					 <<"wamp.registration.list">>,
					 {{2016,5,26},{8,43,3}},
					 exact,random,[],
					 [2004237930060555],
					 0},
	 {erwa_procedure,4881635343555979,<<"ws.wamp.igs.rpc">>,
					 {{2016,5,26},{8,43,7}},
					 exact,single,[],
					 [1446442117595560],
					 0},
	 {erwa_procedure,36293070224888,
					 <<"wamp.registration.lookup">>,
					 {{2016,5,26},{8,43,3}},
					 exact,random,[],
					 [2004237930060555],
					 0},
	 {erwa_procedure,910359775689455,<<"wamp.session.list">>,
					 {{2016,5,26},{8,43,3}},
					 exact,random,[],
					 [2004237930060555],
					 0},
	 {erwa_procedure,3506330608359130,<<"wamp.session.count">>,
					 {{2016,5,26},{8,43,3}},
					 exact,random,[],
					 [2004237930060555],
					 0},
	 {erwa_procedure,4311478342075631,
					 <<"wamp.subscription.lookup">>,
					 {{2016,5,26},{8,43,3}},
					 exact,random,[],
					 [2004237930060555],
					 0}]
	(igs@raspberrypi)2> 
	(igs@raspberrypi)2> 
	(igs@raspberrypi)2> Realm = erlang:list_to_binary("igs_realm").
	<<"igs_realm">>
	(igs@raspberrypi)3> 
	(igs@raspberrypi)3> 
	(igs@raspberrypi)3> erwa_dealer:get_registrations(Realm).
	{ok,#{exact => [4881635343555979],prefix => [],wildcard => []}}
	(igs@raspberrypi)4> 
	(igs@raspberrypi)4> 
	(igs@raspberrypi)4> erwa_dealer:get_registration(4881635343555979, Realm).
	** exception error: no case clause matching 
						{aborted,{no_exists,erwa_proc_igs_realm,{index,[2]}}}
		 in function  erwa_dealer:get_registration/2 (src/erwa_dealer.erl, line 97)
	(igs@raspberrypi)5> 

	(igs@raspberrypi)6> application:which_applications().
	[{igs,"Intelligent Gardening System","0.1.1"},
	 {cowboy,"Small, fast, modular HTTP server.","1.1.0-dev"},
	 {erwa,"a tiny WAMP router","2.0.0_pre"},
	 {ranch,"Socket acceptor pool for TCP protocols.","1.2.1"},
	 {lager,"Erlang logging framework","3.1.0"},
	 {awre,"a simple wamp client library","0.1.0"},
	 {ssl,"Erlang/OTP SSL application","7.3"},
	 {erlang_ale_extension,"Extension for Erlang/ALE. Support more devices to control in Erlang.",
						   "0.1.2"},
	 {wamper,"library of functions used for erwa, both client or router",
			 "0.1.0"},
	 {goldrush,"Erlang event stream processor","0.1.8"},
	 {cowlib,"Support library for manipulating Web protocols.",
			 "1.0.2"},
	 {public_key,"Public key infrastructure","1.1.1"},
	 {runtime_tools,"RUNTIME_TOOLS","1.9.3"},
	 {observer,"OBSERVER version 1","2.1.2"},
	 {mnesia,"MNESIA  CXC 138 12","4.13.3"},
	 {crypto,"CRYPTO","3.6.3"},
	 {asn1,"The Erlang ASN1 compiler version 4.0.2","4.0.2"},
	 {compiler,"ERTS  CXC 138 10","6.0.3"},
	 {syntax_tools,"Syntax tools","1.7"},
	 {pbkdf2,"Erlang PBKDF2 Key Derivation Function","git"},
	 {msgpack,"MessagePack serializer/deserializer","git"},
	 {jsx,"a streaming, evented json parsing toolkit","2.6.2"},
	 {erlang_ale,"Erlang/ALE - Erlang Actor Library for Embedded",
				 "0.1.0"},
	 {stdlib,"ERTS  CXC 138 10","2.8"},
	 {kernel,"ERTS  CXC 138 10","4.2"}]
	(igs@raspberrypi)7> 

thanks for your help,
/Robi

**Comment by ethrbh** [comment]
hello Bas,

Sorry for disturbing you, but I would like to ask you, do you have some nes regarding to this issue?

thanks,
/Robi

**Comment by ethrbh** [comment]
hello,

I started to fix this bug. First I would update this ticket with some instruction about reproduction.

- Update Makefile of erwa
  - add this line into the file: SHELL_OPTS = -sname test
- start erlang shell
  make shell
- start applications
	application:ensure_all_started(cowboy).
	application:ensure_all_started(erwa).
	application:ensure_all_started(awre).

	AppName = erwa.
	Realm = erlang:list_to_binary("erwa_realm_tmp").
	RegisteredRpcUrl = erlang:list_to_binary("ws.wamp.erwa.rpc.tmp").

	Dispatch = cowboy_router:compile([{'_', [{"/erwa", erwa_in_ws, []},{"/", cowboy_static, {priv_file, AppName, "index.html"}},{"/static/[...]", cowboy_static, {priv_dir, AppName, "static"}},{"/[...]", cowboy_static, {priv_dir, AppName, ""}}]}]).

	{ok, HttpPid} = cowboy:start_http(http, 100, [{port, 8081}],[{env, [{dispatch, Dispatch}]}]).

	PrivDir = code:priv_dir(AppName).
	{ok, HttpsPid} = cowboy:start_https(https, 100, [{port, 8082},{cacertfile, PrivDir ++ "/ssl/cowboy-ca.crt"},{certfile, PrivDir ++ "/ssl/server.crt"},{keyfile, PrivDir ++ "/ssl/server.key"}], [{env, [{dispatch, Dispatch}]}]).

	{ok, RanchChild} = ranch:start_listener(erwa_tcp, 5, ranch_tcp, [{port, 5555}], erwa_in_tcp, []).
	ok = erwa:start_realm(Realm).

	erwa_dealer:get_registrations(Realm).
	ets:tab2list(erwa_proc_erwa_realm_tmp).
	erwa_dealer:get_registration(ets:first(erwa_proc_erwa_realm_tmp), Realm). %% **<- Erlang will crashes when execute this command**


br,
/Robi

**Comment by ethrbh** [comment]
hello Bash,

As the fix is already merged to the main, I guess, this issue can be closed. What do you think?

thanks,
/Robi

**Comment by bwegh** [comment]
yes, thought you might have mentioned it in the pull ... closing it now
